name: CI

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Set up Xcode 16.2
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2'

      - name: Install xcpretty
        run: gem install xcpretty

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Build with xcodebuild
        run: |
          xcodebuild -workspace TicTacToe.xcworkspace -scheme TicTacToe \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' \
            CODE_SIGNING_ALLOWED=NO clean build | xcpretty

