name: TicTacToeCore Tests

on:
  pull_request:
    paths:
      - 'TicTacToeCore/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: macos-15 # Xcode 26 is available on macOS 15
    steps:
      - uses: actions/checkout@v3

      - name: Set up Xcode 26.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0-beta'

      - name: Run unit tests
        run: swift test --package-path TicTacToeCore
