name: TicTacToeCore Tests

on:
  pull_request:
    paths:
      - 'TicTacToeCore/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run unit tests
        run: swift test --package-path TicTacToeCore
