name: TicTacToeCore Tests

on:
  pull_request:
    paths:
      - 'TicTacToeCore/**'
      - '.github/workflows/**'

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: '6.0'
      - name: Run unit tests
        run: swift test --package-path TicTacToeCore
